### ISSUE TITLE
deep = false on extending options

### ISSUE THREAD

**Issue by aaronpeterson** [casbloem/vue-luxon#1]
Awesome package you have going!  Just a heads-up that with deep = false on the options extending, setting i18n to even an empty object overwrites the i18n object completely which will break your diffforhumans (among other things).  If one were to blindly copy/paste your usage example (which I would never do, ever) an empty option like i18n would definitely break things. Not sure if the solution was to update the documentation or switch options to deep extend so I'm posting an issue.  I can't see why anyone would change i18n for "day" and not "month" but alas...

**Comment by casbloem** [comment]
the extend method is updated 👍 

(btw you can use the i18n for other languages etc.)
