### ISSUE TITLE
luxon:diffForHumans 

### ISSUE THREAD

**Issue by lbesiche** [casbloem/vue-luxon#13]
When using luxon:diffForHumans, regardless of the timestamp, it will only return "just now".

**Comment by phof** [comment]
Same here, I resolved by downgrading to version 0.6.2.

@casbloem any idea?

**Comment by casbloem** [comment]
It's fixed in version 0.7.1

**Comment by casbloem** [comment]
Never mind. It's still not working.
Ill look into it and publish a fix asap.

**Comment by casbloem** [comment]
Okay it's working now, version 0.7.2

**Comment by phof** [comment]
Thank you, @casbloem! — can you please remove the `console.log` statement from https://github.com/casbloem/vue-luxon/blob/master/vue-luxon.js#L130?

**Comment by casbloem** [comment]
Oops sorry!
I've removed it and published 0.7.3

**Comment by phof** [comment]
Great, thank you for your help @casbloem!
