### ISSUE TITLE
timestamp (unix epoch) support?

### ISSUE THREAD

**Issue by tigrankhachikyan** [casbloem/vue-luxon#15]
Is there a way to read from timestamp (unix epoch) i.e. `1600454930.97649` and format to say 'ymd'?
The Luxon itself seems has method `fromMillis` https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromMillis

I'm trying to do something like 
```
// datetimeVariable =  '1600454930.97649' // i.e. Fri, 18 Sep 2020 20:06:49 GMT

{{ datetimeVariable | luxon:full }}
```

Am I doing something wrong, or this is not supported?

Thanks!

**Comment by casbloem** [comment]
In version 0.7.4 i've added `seconds` (or `unix`) and `millis` to format/parse Unix timestamps.
