### ISSUE TITLE
`:` in filter function names breaks usage in `v-bind` expressions

### ISSUE THREAD

**Issue by riconnon** [casbloem/vue-luxon#16]
Per the docs here https://vuejs.org/v2/guide/filters.html Vue filters should be usable in `v-bind` expressions like
```<component v-bind:name="value| luxon:locale('fulls')">```
When I try to do this, however, I get the error:
```
   invalid expression: Unexpected token ':' in
     value | luxon:locale('fulls')
```

I suspect that the `:` in the filter names is breaking this. Perhaps you'd be willing to add an alias to these using a different naming scheme.

**Comment by casbloem** [comment]
Thank you for pointing this out.
I've added aliases for the filters for now, and i'll make this the default format in the next version.

`luxon:format` => `luxonFormat`
`luxon:locale` => `luxonLocale`
