### ISSUE TITLE
Why is vue-luxon bigger than vue-moment?

### ISSUE THREAD

**Issue by Kotoriii** [casbloem/vue-luxon#17]
Due to Moment.js recommendations to find other alternatives, I am now looking for other JS date parsing libraries for my Vue project.

However, despite complaints about Moment being too big, according to Bundlephobia, the [vue-moment wrapper is still smaller in size](https://bundlephobia.com/result?p=vue-moment@4.1.0) than [vue-luxon](https://bundlephobia.com/result?p=vue-luxon@0.9.0). How can this be?

**Comment by code2prog** [comment]
@Kotoriii I don't think it matters. The main difference in size is due to the fact that vue-luxon uses luxon and not a momentjs which is big

**Comment by casbloem** [comment]
The vue-luxon wrapper is only about 3kb.
So 3kb + full Luxon (70kb) = 73kb

I dont know about the vue-moment library but it seems it doesn't include momentjs, or at least not full momentjs (on bundlephobia)
