### ISSUE TITLE
v-luxon:format through eslint error

### ISSUE THREAD

**Issue by rajagopalx** [casbloem/vue-luxon#2]
Demo:
https://codesandbox.io/s/w7y824rp6w

While using `v-luxon:format('dd-MM-YY')`,  I got eslint parsing error.

**Comment by casbloem** [comment]
Hi,

You should follow the docs on NPM for version 0.5.1.
v-luxon has been removed. I might bring it back in the next version.

Sorry for the struggle.
If you need any help, just ask.

Greets,
Cas Bloem


Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by casbloem** [comment]
You should use the filter for now.

(v-luxon will be added again later)

**Comment by rajagopalx** [comment]
Thank you.
