### ISSUE TITLE
dt.setLocale is not function when using filter

### ISSUE THREAD

**Issue by Iworb** [casbloem/vue-luxon#5]
Latest version doesn't work with default settings.
There's an example: https://codesandbox.io/s/rmnro11o34
There's a `Console` tab in the bottom of the page where you can find error:

> Error in render: "TypeError: dt.setLocale is not a function"

**Comment by casbloem** [comment]
The default serverFormat is ISO.
You use new Date(). This does not return an iso format string.

Take a took at your code now: https://codesandbox.io/s/7k52njmkj0

**Comment by casbloem** [comment]
Dev console errors are coming next version to prevent pointless errors like this.

**Comment by Iworb** [comment]
@casbloem your example is the same as mine with the same error, May I have some working one?

**Comment by casbloem** [comment]
oeps my bad. hit fork instead of save.

here: https://codesandbox.io/s/zn4xxk7rrp
