### ISSUE TITLE
README examples are outdated

### ISSUE THREAD

**Issue by IlyaSemenov** [casbloem/vue-luxon#6]
The top header example:

![vue-luxon-preview](https://user-images.githubusercontent.com/5813001/38711958-00d78e2a-3ec9-11e8-80f2-a16075af06a0.png)

```vue
{{ '2019-01-01' | luxon('MMM, yyyy') }}
```

produces `1 January 2019` rather than expected `Jan, 2019`.

Most other examples also either don't work or crash, for example `{{ luxon.format('dd-MM-YY') }}`  gives *[Vue warn]: Failed to resolve filter: luxon.format*.

After reading the source code I discovered that the correct syntax was:

```vue
{{ '2019-01-01' | luxon:format('MMM, yyyy') }}
```

Isn't it time to update the documentation, or at least add a warning at the top of the page that the syntax is different in the latest version?

**Comment by casbloem** [comment]
I've fixed the typos in the readme. And removed the img for now. Thanks for pointing it out, didn't even realize.
